// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "action_int.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Action_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Action_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_action_5fint_2eproto() {
  protobuf_AddDesc_action_5fint_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "action_int.proto");
  GOOGLE_CHECK(file != NULL);
  Action_descriptor_ = file->message_type(0);
  static const int Action_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, readset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, writeset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, read_deps_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, read_indices_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, read_dep_types_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, write_deps_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, write_indices_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, write_dep_types_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, materialize_),
  };
  Action_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Action_descriptor_,
      Action::default_instance_,
      Action_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Action, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Action));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_action_5fint_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Action_descriptor_, &Action::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_action_5fint_2eproto() {
  delete Action::default_instance_;
  delete Action_reflection_;
}

void protobuf_AddDesc_action_5fint_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020action_int.proto\"\324\001\n\006Action\022\017\n\007readset"
    "\030\001 \003(\005\022\020\n\010writeset\030\002 \003(\005\022\r\n\005state\030\003 \001(\005\022"
    "\021\n\tread_deps\030\004 \003(\004\022\024\n\014read_indices\030\005 \003(\005"
    "\022\026\n\016read_dep_types\030\006 \003(\010\022\022\n\nwrite_deps\030\007"
    " \003(\004\022\025\n\rwrite_indices\030\010 \003(\005\022\027\n\017write_dep"
    "_types\030\t \003(\010\022\023\n\013materialize\030\n \001(\010", 233);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "action_int.proto", &protobuf_RegisterTypes);
  Action::default_instance_ = new Action();
  Action::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_action_5fint_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_action_5fint_2eproto {
  StaticDescriptorInitializer_action_5fint_2eproto() {
    protobuf_AddDesc_action_5fint_2eproto();
  }
} static_descriptor_initializer_action_5fint_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int Action::kReadsetFieldNumber;
const int Action::kWritesetFieldNumber;
const int Action::kStateFieldNumber;
const int Action::kReadDepsFieldNumber;
const int Action::kReadIndicesFieldNumber;
const int Action::kReadDepTypesFieldNumber;
const int Action::kWriteDepsFieldNumber;
const int Action::kWriteIndicesFieldNumber;
const int Action::kWriteDepTypesFieldNumber;
const int Action::kMaterializeFieldNumber;
#endif  // !_MSC_VER

Action::Action()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Action::InitAsDefaultInstance() {
}

Action::Action(const Action& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Action::SharedCtor() {
  _cached_size_ = 0;
  state_ = 0;
  materialize_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Action::~Action() {
  SharedDtor();
}

void Action::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Action::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Action::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Action_descriptor_;
}

const Action& Action::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_action_5fint_2eproto();  return *default_instance_;
}

Action* Action::default_instance_ = NULL;

Action* Action::New() const {
  return new Action;
}

void Action::Clear() {
  if (_has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    state_ = 0;
  }
  if (_has_bits_[9 / 32] & (0xffu << (9 % 32))) {
    materialize_ = false;
  }
  readset_.Clear();
  writeset_.Clear();
  read_deps_.Clear();
  read_indices_.Clear();
  read_dep_types_.Clear();
  write_deps_.Clear();
  write_indices_.Clear();
  write_dep_types_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Action::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 readset = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_readset:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_readset())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_readset())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_readset;
        if (input->ExpectTag(16)) goto parse_writeset;
        break;
      }
      
      // repeated int32 writeset = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_writeset:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_writeset())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_writeset())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_writeset;
        if (input->ExpectTag(24)) goto parse_state;
        break;
      }
      
      // optional int32 state = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_state:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &state_)));
          set_has_state();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_read_deps;
        break;
      }
      
      // repeated uint64 read_deps = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_read_deps:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 32, input, this->mutable_read_deps())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_read_deps())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_read_deps;
        if (input->ExpectTag(40)) goto parse_read_indices;
        break;
      }
      
      // repeated int32 read_indices = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_read_indices:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 40, input, this->mutable_read_indices())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_read_indices())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_read_indices;
        if (input->ExpectTag(48)) goto parse_read_dep_types;
        break;
      }
      
      // repeated bool read_dep_types = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_read_dep_types:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 1, 48, input, this->mutable_read_dep_types())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, this->mutable_read_dep_types())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_read_dep_types;
        if (input->ExpectTag(56)) goto parse_write_deps;
        break;
      }
      
      // repeated uint64 write_deps = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_write_deps:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 56, input, this->mutable_write_deps())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_write_deps())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_write_deps;
        if (input->ExpectTag(64)) goto parse_write_indices;
        break;
      }
      
      // repeated int32 write_indices = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_write_indices:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 64, input, this->mutable_write_indices())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_write_indices())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_write_indices;
        if (input->ExpectTag(72)) goto parse_write_dep_types;
        break;
      }
      
      // repeated bool write_dep_types = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_write_dep_types:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 1, 72, input, this->mutable_write_dep_types())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, this->mutable_write_dep_types())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_write_dep_types;
        if (input->ExpectTag(80)) goto parse_materialize;
        break;
      }
      
      // optional bool materialize = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_materialize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &materialize_)));
          set_has_materialize();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Action::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 readset = 1;
  for (int i = 0; i < this->readset_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->readset(i), output);
  }
  
  // repeated int32 writeset = 2;
  for (int i = 0; i < this->writeset_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->writeset(i), output);
  }
  
  // optional int32 state = 3;
  if (has_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->state(), output);
  }
  
  // repeated uint64 read_deps = 4;
  for (int i = 0; i < this->read_deps_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      4, this->read_deps(i), output);
  }
  
  // repeated int32 read_indices = 5;
  for (int i = 0; i < this->read_indices_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      5, this->read_indices(i), output);
  }
  
  // repeated bool read_dep_types = 6;
  for (int i = 0; i < this->read_dep_types_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(
      6, this->read_dep_types(i), output);
  }
  
  // repeated uint64 write_deps = 7;
  for (int i = 0; i < this->write_deps_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      7, this->write_deps(i), output);
  }
  
  // repeated int32 write_indices = 8;
  for (int i = 0; i < this->write_indices_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      8, this->write_indices(i), output);
  }
  
  // repeated bool write_dep_types = 9;
  for (int i = 0; i < this->write_dep_types_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(
      9, this->write_dep_types(i), output);
  }
  
  // optional bool materialize = 10;
  if (has_materialize()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->materialize(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Action::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 readset = 1;
  for (int i = 0; i < this->readset_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->readset(i), target);
  }
  
  // repeated int32 writeset = 2;
  for (int i = 0; i < this->writeset_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->writeset(i), target);
  }
  
  // optional int32 state = 3;
  if (has_state()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->state(), target);
  }
  
  // repeated uint64 read_deps = 4;
  for (int i = 0; i < this->read_deps_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(4, this->read_deps(i), target);
  }
  
  // repeated int32 read_indices = 5;
  for (int i = 0; i < this->read_indices_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(5, this->read_indices(i), target);
  }
  
  // repeated bool read_dep_types = 6;
  for (int i = 0; i < this->read_dep_types_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBoolToArray(6, this->read_dep_types(i), target);
  }
  
  // repeated uint64 write_deps = 7;
  for (int i = 0; i < this->write_deps_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(7, this->write_deps(i), target);
  }
  
  // repeated int32 write_indices = 8;
  for (int i = 0; i < this->write_indices_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(8, this->write_indices(i), target);
  }
  
  // repeated bool write_dep_types = 9;
  for (int i = 0; i < this->write_dep_types_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBoolToArray(9, this->write_dep_types(i), target);
  }
  
  // optional bool materialize = 10;
  if (has_materialize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->materialize(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Action::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    // optional int32 state = 3;
    if (has_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->state());
    }
    
  }
  if (_has_bits_[9 / 32] & (0xffu << (9 % 32))) {
    // optional bool materialize = 10;
    if (has_materialize()) {
      total_size += 1 + 1;
    }
    
  }
  // repeated int32 readset = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->readset_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->readset(i));
    }
    total_size += 1 * this->readset_size() + data_size;
  }
  
  // repeated int32 writeset = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->writeset_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->writeset(i));
    }
    total_size += 1 * this->writeset_size() + data_size;
  }
  
  // repeated uint64 read_deps = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->read_deps_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->read_deps(i));
    }
    total_size += 1 * this->read_deps_size() + data_size;
  }
  
  // repeated int32 read_indices = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->read_indices_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->read_indices(i));
    }
    total_size += 1 * this->read_indices_size() + data_size;
  }
  
  // repeated bool read_dep_types = 6;
  {
    int data_size = 0;
    data_size = 1 * this->read_dep_types_size();
    total_size += 1 * this->read_dep_types_size() + data_size;
  }
  
  // repeated uint64 write_deps = 7;
  {
    int data_size = 0;
    for (int i = 0; i < this->write_deps_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->write_deps(i));
    }
    total_size += 1 * this->write_deps_size() + data_size;
  }
  
  // repeated int32 write_indices = 8;
  {
    int data_size = 0;
    for (int i = 0; i < this->write_indices_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->write_indices(i));
    }
    total_size += 1 * this->write_indices_size() + data_size;
  }
  
  // repeated bool write_dep_types = 9;
  {
    int data_size = 0;
    data_size = 1 * this->write_dep_types_size();
    total_size += 1 * this->write_dep_types_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Action::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Action* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Action*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Action::MergeFrom(const Action& from) {
  GOOGLE_CHECK_NE(&from, this);
  readset_.MergeFrom(from.readset_);
  writeset_.MergeFrom(from.writeset_);
  read_deps_.MergeFrom(from.read_deps_);
  read_indices_.MergeFrom(from.read_indices_);
  read_dep_types_.MergeFrom(from.read_dep_types_);
  write_deps_.MergeFrom(from.write_deps_);
  write_indices_.MergeFrom(from.write_indices_);
  write_dep_types_.MergeFrom(from.write_dep_types_);
  if (from._has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    if (from.has_state()) {
      set_state(from.state());
    }
  }
  if (from._has_bits_[9 / 32] & (0xffu << (9 % 32))) {
    if (from.has_materialize()) {
      set_materialize(from.materialize());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Action::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Action::CopyFrom(const Action& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Action::IsInitialized() const {
  
  return true;
}

void Action::Swap(Action* other) {
  if (other != this) {
    readset_.Swap(&other->readset_);
    writeset_.Swap(&other->writeset_);
    std::swap(state_, other->state_);
    read_deps_.Swap(&other->read_deps_);
    read_indices_.Swap(&other->read_indices_);
    read_dep_types_.Swap(&other->read_dep_types_);
    write_deps_.Swap(&other->write_deps_);
    write_indices_.Swap(&other->write_indices_);
    write_dep_types_.Swap(&other->write_dep_types_);
    std::swap(materialize_, other->materialize_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Action::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Action_descriptor_;
  metadata.reflection = Action_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
