// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_int.proto

#ifndef PROTOBUF_action_5fint_2eproto__INCLUDED
#define PROTOBUF_action_5fint_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_action_5fint_2eproto();
void protobuf_AssignDesc_action_5fint_2eproto();
void protobuf_ShutdownFile_action_5fint_2eproto();

class Action;

// ===================================================================

class Action : public ::google::protobuf::Message {
 public:
  Action();
  virtual ~Action();
  
  Action(const Action& from);
  
  inline Action& operator=(const Action& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Action& default_instance();
  
  void Swap(Action* other);
  
  // implements Message ----------------------------------------------
  
  Action* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Action& from);
  void MergeFrom(const Action& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated int32 readset = 1;
  inline int readset_size() const;
  inline void clear_readset();
  static const int kReadsetFieldNumber = 1;
  inline ::google::protobuf::int32 readset(int index) const;
  inline void set_readset(int index, ::google::protobuf::int32 value);
  inline void add_readset(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      readset() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_readset();
  
  // repeated int32 writeset = 2;
  inline int writeset_size() const;
  inline void clear_writeset();
  static const int kWritesetFieldNumber = 2;
  inline ::google::protobuf::int32 writeset(int index) const;
  inline void set_writeset(int index, ::google::protobuf::int32 value);
  inline void add_writeset(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      writeset() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_writeset();
  
  // optional int32 state = 3;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 3;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);
  
  // repeated uint64 read_deps = 4;
  inline int read_deps_size() const;
  inline void clear_read_deps();
  static const int kReadDepsFieldNumber = 4;
  inline ::google::protobuf::uint64 read_deps(int index) const;
  inline void set_read_deps(int index, ::google::protobuf::uint64 value);
  inline void add_read_deps(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      read_deps() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_read_deps();
  
  // repeated int32 read_indices = 5;
  inline int read_indices_size() const;
  inline void clear_read_indices();
  static const int kReadIndicesFieldNumber = 5;
  inline ::google::protobuf::int32 read_indices(int index) const;
  inline void set_read_indices(int index, ::google::protobuf::int32 value);
  inline void add_read_indices(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      read_indices() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_read_indices();
  
  // repeated bool read_dep_types = 6;
  inline int read_dep_types_size() const;
  inline void clear_read_dep_types();
  static const int kReadDepTypesFieldNumber = 6;
  inline bool read_dep_types(int index) const;
  inline void set_read_dep_types(int index, bool value);
  inline void add_read_dep_types(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      read_dep_types() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_read_dep_types();
  
  // repeated uint64 write_deps = 7;
  inline int write_deps_size() const;
  inline void clear_write_deps();
  static const int kWriteDepsFieldNumber = 7;
  inline ::google::protobuf::uint64 write_deps(int index) const;
  inline void set_write_deps(int index, ::google::protobuf::uint64 value);
  inline void add_write_deps(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      write_deps() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_write_deps();
  
  // repeated int32 write_indices = 8;
  inline int write_indices_size() const;
  inline void clear_write_indices();
  static const int kWriteIndicesFieldNumber = 8;
  inline ::google::protobuf::int32 write_indices(int index) const;
  inline void set_write_indices(int index, ::google::protobuf::int32 value);
  inline void add_write_indices(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      write_indices() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_write_indices();
  
  // repeated bool write_dep_types = 9;
  inline int write_dep_types_size() const;
  inline void clear_write_dep_types();
  static const int kWriteDepTypesFieldNumber = 9;
  inline bool write_dep_types(int index) const;
  inline void set_write_dep_types(int index, bool value);
  inline void add_write_dep_types(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      write_dep_types() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_write_dep_types();
  
  // optional bool materialize = 10;
  inline bool has_materialize() const;
  inline void clear_materialize();
  static const int kMaterializeFieldNumber = 10;
  inline bool materialize() const;
  inline void set_materialize(bool value);
  
  // @@protoc_insertion_point(class_scope:Action)
 private:
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_materialize();
  inline void clear_has_materialize();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > readset_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > writeset_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > read_deps_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > read_indices_;
  ::google::protobuf::RepeatedField< bool > read_dep_types_;
  ::google::protobuf::int32 state_;
  bool materialize_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > write_deps_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > write_indices_;
  ::google::protobuf::RepeatedField< bool > write_dep_types_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_action_5fint_2eproto();
  friend void protobuf_AssignDesc_action_5fint_2eproto();
  friend void protobuf_ShutdownFile_action_5fint_2eproto();
  
  void InitAsDefaultInstance();
  static Action* default_instance_;
};
// ===================================================================


// ===================================================================

// Action

// repeated int32 readset = 1;
inline int Action::readset_size() const {
  return readset_.size();
}
inline void Action::clear_readset() {
  readset_.Clear();
}
inline ::google::protobuf::int32 Action::readset(int index) const {
  return readset_.Get(index);
}
inline void Action::set_readset(int index, ::google::protobuf::int32 value) {
  readset_.Set(index, value);
}
inline void Action::add_readset(::google::protobuf::int32 value) {
  readset_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Action::readset() const {
  return readset_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Action::mutable_readset() {
  return &readset_;
}

// repeated int32 writeset = 2;
inline int Action::writeset_size() const {
  return writeset_.size();
}
inline void Action::clear_writeset() {
  writeset_.Clear();
}
inline ::google::protobuf::int32 Action::writeset(int index) const {
  return writeset_.Get(index);
}
inline void Action::set_writeset(int index, ::google::protobuf::int32 value) {
  writeset_.Set(index, value);
}
inline void Action::add_writeset(::google::protobuf::int32 value) {
  writeset_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Action::writeset() const {
  return writeset_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Action::mutable_writeset() {
  return &writeset_;
}

// optional int32 state = 3;
inline bool Action::has_state() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Action::set_has_state() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Action::clear_has_state() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Action::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 Action::state() const {
  return state_;
}
inline void Action::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
}

// repeated uint64 read_deps = 4;
inline int Action::read_deps_size() const {
  return read_deps_.size();
}
inline void Action::clear_read_deps() {
  read_deps_.Clear();
}
inline ::google::protobuf::uint64 Action::read_deps(int index) const {
  return read_deps_.Get(index);
}
inline void Action::set_read_deps(int index, ::google::protobuf::uint64 value) {
  read_deps_.Set(index, value);
}
inline void Action::add_read_deps(::google::protobuf::uint64 value) {
  read_deps_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Action::read_deps() const {
  return read_deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Action::mutable_read_deps() {
  return &read_deps_;
}

// repeated int32 read_indices = 5;
inline int Action::read_indices_size() const {
  return read_indices_.size();
}
inline void Action::clear_read_indices() {
  read_indices_.Clear();
}
inline ::google::protobuf::int32 Action::read_indices(int index) const {
  return read_indices_.Get(index);
}
inline void Action::set_read_indices(int index, ::google::protobuf::int32 value) {
  read_indices_.Set(index, value);
}
inline void Action::add_read_indices(::google::protobuf::int32 value) {
  read_indices_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Action::read_indices() const {
  return read_indices_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Action::mutable_read_indices() {
  return &read_indices_;
}

// repeated bool read_dep_types = 6;
inline int Action::read_dep_types_size() const {
  return read_dep_types_.size();
}
inline void Action::clear_read_dep_types() {
  read_dep_types_.Clear();
}
inline bool Action::read_dep_types(int index) const {
  return read_dep_types_.Get(index);
}
inline void Action::set_read_dep_types(int index, bool value) {
  read_dep_types_.Set(index, value);
}
inline void Action::add_read_dep_types(bool value) {
  read_dep_types_.Add(value);
}
inline const ::google::protobuf::RepeatedField< bool >&
Action::read_dep_types() const {
  return read_dep_types_;
}
inline ::google::protobuf::RepeatedField< bool >*
Action::mutable_read_dep_types() {
  return &read_dep_types_;
}

// repeated uint64 write_deps = 7;
inline int Action::write_deps_size() const {
  return write_deps_.size();
}
inline void Action::clear_write_deps() {
  write_deps_.Clear();
}
inline ::google::protobuf::uint64 Action::write_deps(int index) const {
  return write_deps_.Get(index);
}
inline void Action::set_write_deps(int index, ::google::protobuf::uint64 value) {
  write_deps_.Set(index, value);
}
inline void Action::add_write_deps(::google::protobuf::uint64 value) {
  write_deps_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Action::write_deps() const {
  return write_deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Action::mutable_write_deps() {
  return &write_deps_;
}

// repeated int32 write_indices = 8;
inline int Action::write_indices_size() const {
  return write_indices_.size();
}
inline void Action::clear_write_indices() {
  write_indices_.Clear();
}
inline ::google::protobuf::int32 Action::write_indices(int index) const {
  return write_indices_.Get(index);
}
inline void Action::set_write_indices(int index, ::google::protobuf::int32 value) {
  write_indices_.Set(index, value);
}
inline void Action::add_write_indices(::google::protobuf::int32 value) {
  write_indices_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Action::write_indices() const {
  return write_indices_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Action::mutable_write_indices() {
  return &write_indices_;
}

// repeated bool write_dep_types = 9;
inline int Action::write_dep_types_size() const {
  return write_dep_types_.size();
}
inline void Action::clear_write_dep_types() {
  write_dep_types_.Clear();
}
inline bool Action::write_dep_types(int index) const {
  return write_dep_types_.Get(index);
}
inline void Action::set_write_dep_types(int index, bool value) {
  write_dep_types_.Set(index, value);
}
inline void Action::add_write_dep_types(bool value) {
  write_dep_types_.Add(value);
}
inline const ::google::protobuf::RepeatedField< bool >&
Action::write_dep_types() const {
  return write_dep_types_;
}
inline ::google::protobuf::RepeatedField< bool >*
Action::mutable_write_dep_types() {
  return &write_dep_types_;
}

// optional bool materialize = 10;
inline bool Action::has_materialize() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Action::set_has_materialize() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Action::clear_has_materialize() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Action::clear_materialize() {
  materialize_ = false;
  clear_has_materialize();
}
inline bool Action::materialize() const {
  return materialize_;
}
inline void Action::set_materialize(bool value) {
  set_has_materialize();
  materialize_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_action_5fint_2eproto__INCLUDED
